# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"!\n\tWorldData\x12\x14\n\x0c\x61pple_caught\x18\x01 \x01(\x08\"G\n\tAgentData\x12\x1d\n\x15\x64istances_to_obstacle\x18\x01 \x03(\x02\x12\x1b\n\x13\x64istances_to_target\x18\x02 \x03(\x02\"I\n\x07Message\x12\x1e\n\nagent_data\x18\x01 \x01(\x0b\x32\n.AgentData\x12\x1e\n\nworld_data\x18\x02 \x01(\x0b\x32\n.WorldDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WORLDDATA']._serialized_start=14
  _globals['_WORLDDATA']._serialized_end=47
  _globals['_AGENTDATA']._serialized_start=49
  _globals['_AGENTDATA']._serialized_end=120
  _globals['_MESSAGE']._serialized_start=122
  _globals['_MESSAGE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
